import { NgModule } from "@angular/core";
import { MatFormFieldModule, 
    MatInputModule, 
    MatButtonModule, 
    MatSelectModule, 
    MatSidenavModule, 
    MatToolbarModule, 
    MatListModule,
    MatDatepickerModule, 
    MatTabsModule, 
    MatIconModule, 
    MatTableModule, 
    MatBadgeModule, 
    MatChipsModule, 
    MatCardModule,
    MatDividerModule,
    MatCheckboxModule,
    MatGridListModule,
    MatExpansionModule,
    MatButtonToggleModule,
    MatNativeDateModule} from '@angular/material'
    
@NgModule({
    imports:[
        MatFormFieldModule, 
        MatInputModule,
        MatButtonModule,
        MatSelectModule,
        MatSidenavModule,
        MatToolbarModule,
        MatDatepickerModule,
        MatListModule,
        MatTabsModule,
        MatIconModule,
        MatTableModule,
        MatBadgeModule,
        MatChipsModule,
        MatCardModule,
        MatNativeDateModule,
        MatButtonToggleModule,
        MatCheckboxModule,
        MatDividerModule,
        MatGridListModule,
        MatExpansionModule,
    ],
    exports:[
        MatFormFieldModule, 
        MatInputModule,
        MatButtonModule,
        MatSelectModule,
        MatSidenavModule,
        MatToolbarModule,
        MatDatepickerModule,
        MatListModule,
        MatNativeDateModule,
        MatTabsModule,
        MatIconModule,
        MatTableModule,
        MatBadgeModule,
        MatButtonToggleModule,
        MatChipsModule,
        MatCardModule,
        MatCheckboxModule,
        MatDividerModule,
        MatGridListModule,
        MatExpansionModule,
    ]
})

export class MaterialModule{

}